CuaHangBanDienThoai/CuaHangBanDienThoai/Models/ProductDetail.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductDetail()
        {
            this.BillDetail = new HashSet<BillDetail>();
            this.CartItem = new HashSet<CartItem>();
            this.ImportWarehouseDetail = new HashSet<ImportWarehouseDetail>();
            this.OrderDetail = new HashSet<OrderDetail>();
            this.ProductDetailImage = new HashSet<ProductDetailImage>();
        }
    
        public int ProductDetailId { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceSale { get; set; }
        public Nullable<decimal> OriginalPrice { get; set; }
        public string Ram { get; set; }
        public string Capacity { get; set; }
        public Nullable<int> ProductsId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsHome { get; set; }
        public Nullable<bool> IsSale { get; set; }
        public Nullable<bool> IsHot { get; set; }
        public string Alias { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillDetail> BillDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItem> CartItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportWarehouseDetail> ImportWarehouseDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual Products Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDetailImage> ProductDetailImage { get; set; }
    }
}

CuaHangBanDienThoai/CuaHangBanDienThoai/Areas/Admin/Controllers/ProductDetailController.cs
using CuaHangBanDienThoai.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.Threading.Tasks;
using System.Data.Entity;
using Antlr.Runtime.Misc;
using Newtonsoft.Json.Linq;
using System.Drawing;
using System.Diagnostics;
using System.Reflection;
using System.Xml.Linq;
using DocumentFormat.OpenXml.Wordprocessing;
using System.Web.UI.WebControls;

namespace CuaHangBanDienThoai.Areas.Admin.Controllers
{
    public class ProductDetailController : Controller
    {
        // GET: Admin/ProductDetail

        private CUAHANGDIENTHOAIEntities db = new CUAHANGDIENTHOAIEntities();
        [AuthorizeFunction("Quản lý", "Quản trị viên")]
        public ActionResult Index(int? page)
        {
            var items = db.ProductDetail.OrderByDescending(x => x.ProductDetailId).ToList();

            if (items != null)
            {
                int pageSize = 10;
                int pageNumber = (page ?? 1);

                var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

                var products = db.ProductDetail.ToList();
                bool isAdmin = Session["AdminRole"] != null && Session["AdminRole"].ToString().Equals("Quản trị viên");

                var product = db.ProductCategory.ToList();
                ViewBag.ProductCategory = new SelectList(product, "ProductCategoryId", "Title");
               

                ViewBag.IsAdmin = isAdmin;
              
                ViewBag.PageSize = pageSize;
                ViewBag.Page = page;
                return View(items.ToPagedList(pageNumber, pageSize));

            }
            else
            {
                ViewBag.txt = "Không tồn tại sản phẩm";
                return View();
            }
        }




        [HttpGet]
        public JsonResult GetProductbyCategoryId(int? categoryid)
        {
            if(categoryid > 0)
            {
                var products = db.Products.Where(x => x.ProductCategoryId == categoryid)
                    .Select(p => new
                    {
                        p.Title,
                        p.ProductsId
                    }).ToList() ;
                return Json(products, JsonRequestBehavior.AllowGet);
            }
            return Json(null, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Partail_ProductDetailById(int? productid , int? categoryid)
        {
        
            if(productid>0 && categoryid <=0)
            {
                var pro = db.Products.Find(productid);
                var productdetail =db.ProductDetail.Where(x=>x.ProductsId==productid).OrderBy(x=>x.ProductDetailId).ToList();
                if (productdetail != null && pro !=null)
                {
                    ViewBag.Title = "Sản phẩm con theo " + pro.ProductCategory.Title.Trim() + " " + pro.Title.Trim();
                    return PartialView(productdetail);
                }
            }
            else
            {
                var pro = db.ProductCategory.Find(categoryid);
                var productdetail =
                                    from pd in db.ProductDetail
                                    join p in db.Products on pd.ProductsId equals p.ProductsId into pJoin
                                    from p in pJoin.DefaultIfEmpty()
                                    join pc in db.ProductCategory on p.ProductCategoryId equals pc.ProductCategoryId into pcJoin
                                    from pc in pcJoin.DefaultIfEmpty()
                                    where pc.ProductCategoryId == categoryid
                                    select pd;

                if (productdetail != null && pro != null)
                {
                    ViewBag.Title = "Sản phẩm con theo " + pro.Title.Trim();
                    return PartialView(productdetail);
                }
            }
            return PartialView();
        }

        [HttpGet]
        public ActionResult SearchProduct(string key)
        {
            if (!string.IsNullOrEmpty(key))
            {
                string alias = CuaHangBanDienThoai.Models.Common.Filter.FilterChar(key.Trim().ToLower());
                string keyLower = key.Trim().ToLower();

                var query = from pd in db.ProductDetail
                            join p in db.Products on pd.ProductsId equals p.ProductsId
                            join pc in db.ProductCategory on p.ProductCategoryId equals pc.ProductCategoryId into pcJoin
                            from pc in pcJoin.DefaultIfEmpty()
                            join pcx in db.ProductCompany on p.ProductCompanyId equals pcx.ProductCompanyId into pcxJoin
                            from pcx in pcxJoin.DefaultIfEmpty()
                            where
                                pd.IsActive == true &&
                                (
                                    (pc.Title.Trim().Contains(keyLower.Trim()) || pc.Alias.Trim().Contains(alias.Trim())) ||
                                    (pcx.Title.Trim().Contains(keyLower.Trim()) || pcx.Alias.Trim().Contains(alias.Trim())) ||
                                    p.Title.Trim().Contains(keyLower.Trim()) ||
                                    pd.Color.Trim().Contains(keyLower.Trim()) ||
                                    pd.Capacity.Contains(keyLower)
                                )
                            select pd;
             


                var productdetail =  query
                    .OrderBy(pd=>pd.ProductDetailId)

                    .ToList();

                ViewBag.Key = key.Trim();
                

                return PartialView(productdetail);
            }


            return PartialView();
        }


        [AuthorizeFunction("Quản trị viên")]
        public  ActionResult Add(int? productid)
        {

            if (db.Products.Any())
            {
                var productlist = db.Products
                    .Where(pro => pro.ProductCategory != null)
                    .Select(pro => new ListProductId
                    {
                        ProductsId = pro.ProductsId,
                        Image = pro.Image,
                        Title = pro.ProductCategory.Title.Trim() + " " + pro.Title.Trim(),
                        IsCheck = productid.HasValue && productid > 0 && productid == pro.ProductsId 
                    })
                    .ToList();

                ViewBag.ProductList = productlist;
                return View();
            }
      
            return View();
        }
        [AuthorizeFunction("Quản trị viên")]
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<ActionResult> Add(ProductDetail model ,Admin_AddProductDetail req, List<string> Images, List<int> rDefault)
        {
            using (var dbContextTransaction = db.Database.BeginTransaction())
            {
                try {
                    if (ModelState.IsValid)
                    {
                        if (Images == null  )
                        {
                            return Json(new { Success = false, Code = -2, msg = "Vui lòng chọn ít nhất 3 ảnh sản phẩm" });
                           
                        }


                            if (req.ProductsId <=0)
                        {

                            return Json(new { Success = false, Code = -2, msg = "Danh mục hoặc hãng" });

                        }
                        var product = await db.Products.FirstOrDefaultAsync(x => x.ProductsId == req.ProductsId);


                       
                        if (product == null)
                        {
                           
                            return Json(new { Success = false, Code = -2, msg = "Danh mục hoặc hãng" });

                        }
                
                        string rawAlias = $"{product.Alias+"-"}{req.Color + "-"} {req.Ram + "-"}{req.Capacity + "-"}".Trim();
                        string  alias = CuaHangBanDienThoai.Models.Common.Filter.FilterChar(rawAlias).Trim();
                        var checkDetails = await db.ProductDetail.FirstOrDefaultAsync(x => x.Alias == alias.Trim());
                        if (checkDetails != null)
                        {
                            return Json(new { Success = false, Code = -3, msg = "Sản phẩm đã tồn tại" });
                        }
                        else
                        {
                            model.Color = req.Color.Trim();
                            model.Price = req.Price;
                            model.PriceSale = req.PriceSale;
                            model.OriginalPrice = req.OriginalPrice;
                            model.Ram = req.Ram.Trim();
                            model.Capacity = req.Capacity.Trim();
                            model.ProductsId = req.ProductsId;
                            model.Ram = req.Ram.Trim();
                            model.IsActive = false;
                            model.IsHome = false;
                            model.IsSale = false;
                            model.IsHot = false;
                            model.Alias = alias.Trim();
                            model.Quantity = req.Quantity;


                            db.ProductDetail.Add(model);
                            db.SaveChanges();


                            if (Images != null )
                            {
                                if (Images.Count < 2 && rDefault == null || rDefault.Count == 0)
                                {
                                    return Json(new { Success = false, Code =-2 , msg = "Vui lòng chọn ảnh đại diện sản phẩm" });
                                }

                                for (int i = 0; i < Images.Count; i++)
                                {
                                    bool isDefault = (i + 1 == rDefault[0]);

CuaHangBanDienThoai/CuaHangBanDienThoai/Views/ProductDetail/Capacity.cshtml
@model List<CuaHangBanDienThoai.Models.ProductColorViewModel>
@if (Model != null && ViewBag.Alias != null && ViewBag.Capacity != null)
{
    foreach (var item in Model)
    {
        if (ViewBag.Capacity == item.Capacity)
        {
            <a href="/san-pham/@ViewBag.Alias.Trim()-dl@(item.Capacity.Trim())" data-index="0" class="box03__item item act">@item.Capacity.Trim()</a>
        }
        else
        {
            <a href="/san-pham/@ViewBag.Alias.Trim()-dl@(item.Capacity.Trim())" data-index="0" class="box03__item item ">@item.Capacity.Trim()</a>
        }


    }
}

CuaHangBanDienThoai/CuaHangBanDienThoai/Views/ProductDetail/Index.cshtml
@model PagedList.PagedList<CuaHangBanDienThoai.Models.ProductDetail>
@using CuaHangBanDienThoai.Common
@using PagedList.Mvc;
@{
    ViewBag.Title = "Cửa hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/css/client/ProductIndex.css" rel="stylesheet" />
<style>
</style>

<div class="container container_Index ">
    <div class="row">
        <div class="col product_section clearfix">
            <!-- Breadcrumbs -->
            <ul class="breadcrumbs mb-1 pl-0 pt-2 d-flex align-items-center " style="margin:0!important">
                <li class="breadcrumb-item m-0 p-0"><a href="/cua-hang">Sản phẩm</a></li>
            </ul>

            <!-- Sidebar -->

            <div class="sidebar">
                <div class="sidebar_section ">
                    <div class="sidebar_title">
                        <h5>Mục sản phẩm</h5>
                    </div>
                    @Html.Action("MenuLeft", "Menu", new { Alias = ViewBag.Alias })
                </div>
            </div>

            <!-- Main Content -->

            <div class="main_content">

                <!-- Products -->

                <div class="products_iso">
                    <div class="row">
                        <div class="col products_col p-0">

                            <!-- Product Grid -->

                            <div class=" product__grid">
                                @if (Model != null)
                                {
                                    foreach (var item in Model)
                                    {
                                        @functions {

                                            public decimal CalculateDiscountPercentage(decimal originalPrice, decimal salePrice)
                                            {
                                                if (originalPrice == 0 || salePrice >= originalPrice)
                                                {
                                                    return 0;
                                                }

                                                decimal discount = 1 - (salePrice / originalPrice);
                                                return (int)(discount * 100);
                                            }
                                        }
                                        var strImg = "";
                                        var CheckImage = item.ProductDetailImage.FirstOrDefault(x => x.IsDefault == true);

                                        var Name = item.Products.ProductCategory.Title.Trim() + "   " + item.Products.Title.Trim();
                                        var detail = item.Ram.Trim() + "-" + item.Capacity.Trim();
                                        if (CheckImage != null)
                                        {
                                            strImg = CheckImage.Image;
                                        }
                                        else
                                        {
                                            strImg = "~/Content/css/admin/login/images/logoWeb.png";
                                        }
                                        <div class="col-lg-3 col-md-4 col-sm-6 col-6 mt-2 mb-2  listproduct product__grid__item" id="product-container-@item.ProductsId">
                                            <div class="  product__item" @*style="border: 1px solid #eaecf0 !important; border-radius: 8px !important;"*@>


                                                <a href="/san-pham/@item.Alias" class="product_image__item">
                                                    <img src="@(item.Products?.Image ?.Trim()?? "/images/logo/logoWeb.png")" alt="@Name ">

                                                </a>

                                                @if (item.PriceSale > 0)
                                                {
                                                    <div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center">
                                                        @{
                                                            decimal originalPrice = Convert.ToDecimal(item.Price);
                                                            decimal salePrice = Convert.ToDecimal(item.PriceSale);
                                                            decimal discountPercentage = CalculateDiscountPercentage(originalPrice, salePrice);
                                                        }

                                                        <span @(discountPercentage > 0 ? "" : "hide")>- @discountPercentage.ToString("0")%</span>
                                                    </div>
                                                }

                                                <div class="product_info" style="display: flex !important; flex-direction: column !important;  align-items: flex-start !important; ">
                                                    <a href="/san-pham/@item.Alias.Trim()" class="pl-0 product_name mb-1" style="">
                                                        <h6 class="product_name mt-0" style=" text-align: center;margin-bottom:0 !important; overflow: hidden; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical;">
                                                            @Name.Trim()

                                                        </h6>

                                                    </a>

                                                    <div class="item-compare gray-bg mb-0">
                                                        <span>Super Retina XDR</span>
                                                        <span> @($"{item.Products.Screensize.Trim()}")" </span>
                                                    </div>
                                                    @Html.Action("Capacity", "Product", new { productid = item.ProductsId, Capacity = item.Capacity.Trim() })


                                                    @if (item.PriceSale > 0)
                                                    {
                                                        <div class="price-container align-items-center text-center pr-0 pl-0">
                                                            <strong class="price">@($"{Common.FormatNumber(item.PriceSale)}đ")</strong>
                                                            <div class="box-p">
                                                                <p class="price-old black">@($"{Common.FormatNumber(item.Price)}đ")</p>

                                                            </div>
                                                        </div>

                                                    }
                                                    else
                                                    {
                                                        <div class="price-container">
                                                            <strong class="price">@($"{Common.FormatNumber(item.Price)}đ")</strong>

                                                        </div>
                                                    }

                                                </div>
                                            </div>
                                        </div>


                                    }
                                }
                                else
                                {
                                    <!-- Handle the case when Model is null -->
                                }
                            </div>


                            <!-- Product Sorting -->
                            <hr />
                            <div class="product_sorting_container product_sorting_container_bottom clearfix">

                                @if (Model != null && Model.Any())
                                {


                                    <div class="pages d-flex flex-row align-items-center pagesGroup">
                                        <div class="col-12 d-flex justify-content-center text-dark">
                                            <nav aria-label="Page navigation">
                                                <ul class="pagination pagination-sm">
                                                    <li class="page-item @(Model.PageNumber == 1 ? "disabled" : "")">
                                                        <a class="page-link text-dark" href="@Url.Action("Index", new { page = 1 })" aria-label="First">
                                                            <span aria-hidden="true">Đầu</span>
                                                        </a>
                                                    </li>
                                                    <li class="page-item @(Model.PageNumber == 1 ? "disabled" : "")">
                                                        <a class="page-link text-dark" href="@Url.Action("Index", new { page = Model.PageNumber - 1 })" aria-label="Previous">
                                                            <span aria-hidden="true">&laquo;</span>
                                                        </a>
                                                    </li>
                                                    @for (int i = Model.PageNumber; i <= Model.PageNumber + 4 && i <= Model.PageCount; i++)
                                                    {
                                                        <li class="page-item @(Model.PageNumber == i ? "active" : "")">
                                                            <a class="page-link text-dark" href="@Url.Action("Index", new { page = i })">@i</a>
                                                        </li>
                                                    }

                                                    <li class="page-item @(Model.PageNumber == Model.PageCount ? "disabled" : "")">
                                                        <a class="page-link text-dark" href="@Url.Action("Index", new { page = Model.PageNumber + 1 })" aria-label="Next">
                                                            <span aria-hidden="true">&raquo;</span>
                                                        </a>
                                                    </li>
                                                    <li class="page-item @(Model.PageNumber == Model.PageCount ? "disabled" : "")">
                                                        <a class="page-link text-dark" href="@Url.Action("Index", new { page = Model.PageCount })" aria-label="Last">
                                                            <span aria-hidden="true">Cuối</span>
                                                        </a>
                                                    </li>
                                                </ul>
                                            </nav>
                                        </div>
                                    </div>
                                    <div class="col-12 text-center align-items-center  m-0">
                                        <span class="showing_results m-0">
                                            Hiển thị @Model.FirstItemOnPage – @Model.LastItemOnPage của @Model.TotalItemCount sản phẩm
                                        </span>
                                    </div>
                                }

                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).on('click', '.capacity-link', function () {
        const proId = $(this).data('pro-id');
        const productDetailId = $(this).data('product-detail-id');
        const capacity = $(this).data('capacity');

        const detailContainer = $('#product-container-' + productDetailId);
        console.log("proId", proId);
        console.log("productDetailId", productDetailId);
        console.log("capacity", capacity);
        $.ajax({
            url: '@Url.Action("Partial_DetailByCapactity", "ProductDetail")',
            type: 'GET',
            data: {
                proId: proId,
                productDetailId: productDetailId,
                capcity: capacity
            },
            success: function (result) {
                $('#product-container-' + proId).html(result);

            },
            error: function () {
                alert('Failed to load product details.');
            }
        });
    });



    $(document).ready(function () {

        $('.sidebar_title h5').click(function (e) {
            e.stopPropagation();
            $('.sidebar_categories').toggleClass('show');
        });


        $(document).click(function (e) {
            if (!$(e.target).closest('.sidebar_categories, .sidebar_title').length) {
                $('.sidebar_categories').removeClass('show');
            }
        });
    });
</script>

CuaHangBanDienThoai/CuaHangBanDienThoai/Views/ProductDetail/Partail_ColorByProductsId.cshtml
@model List<CuaHangBanDienThoai.Models.ProductColorViewModel>
@if (Model != null && ViewBag.Alias!=null && ViewBag.Color!=null)
{
    foreach (var item in Model)
    {
        string color = CuaHangBanDienThoai.Models.Common.Filter.FilterChar(item.Color.Trim()).Trim();
        if (ViewBag.Color.Trim() == item.Color.Trim())
        {

            <a href="/san-pham/@(ViewBag.Alias.Trim())-@(item.Capacity.Trim())-color@(@item.Color.Trim().Replace(" ", "-"))" data-color="1195" data-code="0131491004251" data-color="@item.Color.Trim()" class="box03__item color item act"><i style="background-color:#BAB4A9"></i>@item.Color.Trim()</a>
        }
        else
        {
            <a href="/san-pham/@(ViewBag.Alias.Trim())-@(item.Capacity.Trim())-color@(@item.Color.Trim().Replace(" ", "-"))" data-color="1195" data-code="0131491004251" class="box03__item color item "><i style="background-color:#BAB4A9"></i>@item.Color.Trim()</a>
        }




    }
}

CuaHangBanDienThoai/CuaHangBanDienThoai/Views/ProductDetail/Partial_DetailByCapactity.cshtml
@model CuaHangBanDienThoai.Models.ProductDetail
@using CuaHangBanDienThoai.Common;

<link href="~/Content/css/client/ProductIndex.css" rel="stylesheet" />
@if (Model != null)
{
    @functions {

        public decimal CalculateDiscountPercentage(decimal originalPrice, decimal salePrice)
        {
            if (originalPrice == 0 || salePrice >= originalPrice)
            {
                return 0;
            }

            decimal discount = 1 - (salePrice / originalPrice);
            return (int)(discount * 100);
        }
    }

    var strImgCapcity = Model.ProductDetailImage.FirstOrDefault(x => x.IsDefault == true)?.Image ?? "~/Content/css/admin/login/images/logoWeb.png";

    var Name = Model.Products.ProductCategory.Title.Trim() + " " + Model.Products.Title.Trim();
    var detail = Model.Ram.Trim() + "-" + Model.Capacity.Trim();



  
        <div class="  product__item listproduct" style="border: 1px solid #eaecf0 !important; border-radius: 8px !important;">


            <a href="/san-pham/@Model.Alias" class="product_image__item">
                <img src="@(Model.Products?.Image ?.Trim()?? "/images/logo/logoWeb.png")"  alt="@Name ">
            </a>

            @if (Model.PriceSale > 0)
            {
                <div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center">
                    @{
                        decimal originalPrice = Convert.ToDecimal(Model.Price);
                        decimal salePrice = Convert.ToDecimal(Model.PriceSale);
                        decimal discountPercentage = CalculateDiscountPercentage(originalPrice, salePrice);
                    }

                    <span @(discountPercentage > 0 ? "" : "hide")>- @discountPercentage.ToString("0")%</span>
                </div>
            }

        <div class="product_info" style="display: flex !important; flex-direction: column !important;  align-items: flex-start !important; ">
            <a href="/san-pham/@Model.Alias.Trim()" class="pl-0 product_name mb-1" style="">
                <h6 class="product_name mt-0" style=" text-align: center;margin-bottom:0 !important; overflow: hidden; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical;">
                    @Name.Trim()

                </h6>

            </a>

            <div class="item-compare gray-bg mb-0">
                <span>Super Retina XDR</span>
                <span> @($"{Model.Products.Screensize.Trim()}")" </span>
            </div>
            @Html.Action("Capacity", "Product", new { productid = Model.ProductsId, Capacity = Model.Capacity.Trim() })


            @if (Model.PriceSale > 0)
            {
                <div class="price-container">
                    <strong class="price">@($"{Common.FormatNumber(Model.PriceSale)}đ")</strong>
                    <div class="box-p">
                        <p class="price-old black">@($"{Common.FormatNumber(Model.Price)}đ")</p>
                      
                    </div>
                </div>

            }
            else
            {
                <div class="price-container">
                    <strong class="price">@($"{Common.FormatNumber(Model.Price)}đ")</strong>

                </div>

            }

        </div>
            @*<div class="red_button add_to_cart_button">
                    <a href="javascript:void(0);" class="btnbuynow btnAddtoCartItem" data-productid="@item.ProductsId">Mua ngay</a>
                </div>*@
        </div>
    @*</div>*@
}