CuaHangBanDienThoai/CuaHangBanDienThoai/Models/ProductCompany.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductCompany()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int ProductCompanyId { get; set; }
        public string Title { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Modifiedby { get; set; }
        public string Alias { get; set; }
        public string Icon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}

CuaHangBanDienThoai/CuaHangBanDienThoai/Areas/Admin/Controllers/ProductCompanyController.cs
using CuaHangBanDienThoai.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace CuaHangBanDienThoai.Areas.Admin.Controllers
{
    public class ProductCompanyController : Controller
    {
        // GET: Admin/ProductCompany

    private     CUAHANGDIENTHOAIEntities db = new CUAHANGDIENTHOAIEntities();
        [AuthorizeFunction("Quản lý", "Quản trị viên")]

        public ActionResult Index(int? page )
        {
            var items = db.ProductCompany.OrderByDescending(x => x.ProductCompanyId).ToList();

            if (items != null)
            {
                int pageSize = 10;
                int pageNumber = (page ?? 1);
           
                bool isAdmin = Session["AdminRole"] != null && Session["AdminRole"].ToString().Equals("Quản trị viên");
                ViewBag.IsAdmin = isAdmin;

                var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

                var products = db.ProductCompany.ToList();

                ViewBag.Count = products.Count;
                ViewBag.PageSize = pageSize;
                ViewBag.Page = page;
                return View(items.ToPagedList(pageNumber, pageSize));

            }
            else
            {
                ViewBag.txt = "Không tồn tại sản phẩm";
                return View();
            }
        }

        [AuthorizeFunction( "Quản trị viên")]
        public ActionResult Add()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(ProductCompany model, Admin_AddProductCompany req, List<string> Images, List<int> rDefault)
        {
            using (var dbContextTransaction = db.Database.BeginTransaction())
            {
                try
                {
                    if (req.Title == null)
                    {
                        return Json(new { Success = false, Code = -2, msg = "Vui lòng nhập tên hãng" });
                    }
                    string alias= CuaHangBanDienThoai.Models.Common.Filter.FilterChar(req.Title.Trim());

                    var item = await db.ProductCompany.FirstOrDefaultAsync(x => x.Alias == alias.Trim());
                    if (item != null)
                    {
                        return Json(new { Success = false, Code = -2, msg = "Hãng đã tồn tại" });
                    }

                    if (Images == null || Images.Count == 0)
                    {
                        return Json(new { Success = false,Code =-2,msg="Vui lòng chọn logo hãng"});
                    }
                   


                    AccountEmployee nvSession = (AccountEmployee)Session["user"];
                    var checkStaff = db.Employee.SingleOrDefault(row => row.EmployeeId == nvSession.EmployeeId);
                    model.Icon = Images[0];
                    model.Title = req.Title;
                    model.CreatedDate=DateTime.Now;
                    model.CreatedBy = checkStaff.NameEmployee.Trim();
                    model.Alias = CuaHangBanDienThoai.Models.Common.Filter.FilterChar(req.Title.Trim());
                    db.ProductCompany.Add(model);
                    db.SaveChanges();
                    dbContextTransaction.Commit();
                    return Json(new { Success = true, Code = 1 });


                }
                catch (Exception ex)
                {
                    dbContextTransaction.Rollback();

                    Console.WriteLine(ex.Message);
                    return Json(new { Success = false, Code = -100 });


                }
            }
        }

        [AuthorizeFunction("Quản lý", "Quản trị viên")]
        public async Task<ActionResult> Detail(string alias)
        {
            if (alias == null)
            {
                return View();
            }
            var item = await db.ProductCompany.FirstOrDefaultAsync(x => x.Alias == alias.Trim());
            if (item != null)
            {
                ViewBag.Name = item.Title.Trim();
                return View(item);
            }
            return View();
        }
        public ActionResult Partail_ProDetailByCompany(int? companyid)
        {
            if(companyid!=null && companyid > 0)
            {
                var product = from pd in db.ProductDetail
                              join p in db.Products on pd.ProductsId equals p.ProductsId 
                              join pcny in db.ProductCompany on p.ProductCompanyId equals pcny.ProductCompanyId    
                              where pcny.ProductCompanyId == companyid  
                              select pd;
                var title = db.ProductCompany.Find(companyid);
                if (title!=null && product != null)
                {
                    bool isAdmin = Session["AdminRole"] != null && Session["AdminRole"].ToString().Equals("Quản trị viên");
                    ViewBag.IsAdmin = isAdmin;
                    ViewBag.Title= title.Title.Trim();
                    return PartialView(product);
                }
            }
            return PartialView();   
        }


        [AuthorizeFunction( "Quản trị viên")]
        public async Task<ActionResult> Edit(string alias)
        {
            if (alias == null)
            {
                return View();
            }
            var item = await db.ProductCompany.FirstOrDefaultAsync(x => x.Alias == alias.Trim());
            if (item != null)
            {
                ViewBag.Name = item.Title.Trim();
                return View(item);
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductCompany model,List<string> Images, List<int> rDefault)
        {
            using (var dbContextTransaction = db.Database.BeginTransaction())
            {
            try {
                    if (ModelState.IsValid)
                    {
                        var existingcompany = db.ProductCompany.Find(model.ProductCompanyId);
                        if (existingcompany == null)
                        {
                          


                            return Json(new { Success = false, Code = -2, msg = "Hãng đã tồn tại" });
                        }

                        existingcompany.Alias = Models.Common.Filter.FilterChar(model.Title.Trim());
                        AccountEmployee nvSession = (AccountEmployee)Session["user"];
                        var checkStaff = db.Employee.SingleOrDefault(row => row.EmployeeId == nvSession.EmployeeId);

                        existingcompany.Modifiedby = checkStaff.NameEmployee.Trim();

                        existingcompany.ModifiedDate = DateTime.Now;
            
                        existingcompany.Title = model.Title;

                        existingcompany.CreatedDate = model.CreatedDate;
                        existingcompany.CreatedBy = model.CreatedBy;
                        existingcompany.Alias = CuaHangBanDienThoai.Models.Common.Filter.FilterChar(model.Title.Trim());

             
                        if (!string.IsNullOrEmpty(model.Icon))
                        {
                            existingcompany.Icon = model.Icon;
                        }

                        db.Entry(existingcompany).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                        dbContextTransaction.Commit();

                        return Json(new { Success = true, Code = 1 });
                    }
                    else
                    {
                        var errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage);
                        return Json(new { Success = false, Code = -2, msg = "Vui nhập đủ thông tin" });
                    }

                }
                catch(Exception ex) {

                    dbContextTransaction.Rollback();

                    Console.WriteLine(ex.Message);
                    return Json(new { Success = false, Code = -100 });

                }
            }
        }
       

    }
}

CuaHangBanDienThoai/CuaHangBanDienThoai/Areas/Admin/Views/ProductCompany/Detail.cshtml
@model CuaHangBanDienThoai.Models.ProductCompany
@{
    ViewBag.Title = "Hãng " + (ViewBag.Name ?? "");
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="bg-sgCommet" style="display: none ">

</div>


<div id="popupCommmet" style="display: none">

</div>
<div class="container-fluid">
    @if (Model != null)
    {


        <div class="row">
            <div class="col-6">
                <h1 class="h3 mb-2 text-gray-800">Hệ thống quản lý </h1>

            </div>
            <div class="col-6 ">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/he-thong-quan-ly">Trang chủ </a></li>
                    <li class="breadcrumb-item"><a href="/hang-san-pham">Hãng sản phẩm </a></li>
                    <li class="breadcrumb-item active">Chi tiết  @ViewBag.Name</li>

                </ol>

            </div>
        </div>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header bg-white py-3">

                <div class="row">
                    <div class="col-lg-3">
                        <div class="single_product_pics">
                            <div class="row">
                                <div class="col-lg-12 image_col order-lg-2 order-1">
                                    <div class="single_product_image text-center">

                                        <img src="@Model.Icon" alt="@Model.Title" style="max-width:80%" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-9">


                        <div class="product_details">
                            <div class="product_details_title">

                                <div class="row">
                                    <div class="col-lg-8">
                                        <h2>@Model.Title.Trim()</h2>
                                    </div>
                                    @if (ViewBag.IsAdmin != null && (bool)ViewBag.IsAdmin)
                                    {
                                        <div class="col-md-4 text-right">
                                            <a href="/chinh-sua-hang/@Model.Alias" class="btn btn-warning text-white">
                                                Chỉnh sửa
                                            </a>

                                        </div>

                                    }

                                </div>
                                <hr class="col-12" />

                            </div>
                            <ul class="nav nav-pills mb-4">
                                <li class="nav-item"><a class="nav-link active" href="#activity" data-toggle="tab">Thông tin chung</a></li>



                            </ul>
                            <hr class="col-12" />
                            <div class="tab-content">
                                <div class="active tab-pane" id="activity">
                                    <div class="col-12">
                                        <h5 class="text-black">Thông tin hãng sản phẩm  @Model.Title.Trim()</h5>
                                        <p class="d-flex flex-row">
                                            Mã hãng :
                                            <span class="text-gray-600"> @Model.Alias</span>
                                        </p>

                                        <p class="d-flex flex-row">Tạo ngày :      <span class="text-gray-600">  @Model.CreatedDate.ToString("dd/MM/yyyy")</span></p>
                                        <p class="d-flex flex-row">Tạo bởi :   <span class="text-gray-600"> @Model.CreatedBy</span></p>
                                        <p class="d-flex flex-row">
                                            @Html.Raw((Model.ModifiedDate != null)
                                                ? $" Chỉnh sửa ngày: <span class=\"text-gray-600\">  {Model.ModifiedDate:dd/MM/yyyy} </span>"
                                                : "")
                                        </p>

                                        <p class="d-flex flex-row"></p>

                                        @Html.Raw((Model.Modifiedby != null)
                                                ? $"Chỉnh sửa bởi: <span class=\"text-gray-600\">  {Model.Modifiedby} </span>"
                                                : "")

                                    </div>
                                </div>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-6">
                <h1 class="h3 mb-2 text-gray-800">Hệ thống quản lý </h1>

            </div>
            <div class="col-6 ">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/he-thong-quan-ly">Trang chủ </a></li>
                    <li class="breadcrumb-item"><a href="/loai-san-pham">Hãng sản phẩm </a></li>

                </ol>

            </div>
        </div>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header bg-white py-3">

                <div class="col-12">
                    <p class="text-danger text-danger">
                        Không tồn tại bảng ghi nào !!!
                    </p>
                </div>

            </div>
        </div>
    }

</div>


<div class="container-fluid">
    @if (Model != null)
    {
        <div class="card shadow mb-4">
            @Html.Action("Partail_ProDetailByCompany", "ProductCompany", new { companyid = Model.ProductCompanyId })
        </div>
    }
</div>

CuaHangBanDienThoai/CuaHangBanDienThoai/Areas/Admin/Views/ProductCompany/Edit.cshtml
@model CuaHangBanDienThoai.Models.ProductCompany
@{
    ViewBag.Title = "Chỉnh sửa hãng" + (ViewBag.Name ?? "");
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    @if (Model != null)
    {
        <div class="row">
            <div class="col-6">
                <h1 class="h3 mb-2 text-gray-800">Hệ thống quản lý</h1>
            </div>
            <div class="col-6 ">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/he-thong-quan-ly">Trang chủ</a></li>
                    <li class="breadcrumb-item"><a href="/hang-san-pham">Hãng sản phẩm</a></li>
                    <li class="breadcrumb-item active">Chỉnh sửa danh mục @(ViewBag.Name ??" " )</li>
                </ol>
            </div>
        </div>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header bg-white py-3">
                @using (Html.BeginForm("Edit", "ProductCompany", FormMethod.Post, new { enctype = "multipart/form-data", id = "editForm" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    @Html.HiddenFor(x => x.ProductCompanyId)
                    @Html.HiddenFor(x => x.CreatedDate)
                    @Html.HiddenFor(x => x.CreatedBy)


                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <input type="hidden" id="txtImage" name="Icon" />
                    <div class="row">
                        <div class="col-lg-3">
                            <div class="single_product_pics">
                                <div class="row">
                                    <div class="col-lg-12 image_col order-lg-2 order-1">
                                        <div class="single_product_image text-center">
                                            <div class="container-anh-cu" style="position: relative; display: inline-block;">
                                                <img id="img-cu" src="@Model.Icon" alt="@Model.Title" style="max-width:80%;" />
                                                <input type="button" class="btn btn-primary" value="Đổi ảnh" onclick="BrowseServer('txtImage');" style="position: absolute; top: 0; left: 0;" />
                                            </div>
                                            <div class="container-anh-moi" style="display:none; position: relative;">
                                                <img id="img-moi" src="#" alt="Ảnh mới" style="max-width:80%;" />
                                                <input type="button" class="btn btn-primary" value="Đổi ảnh" onclick="BrowseServer('txtImage');" style="position: absolute; top: 0; left: 0;" />
                                            </div>
                                            <input type="file" id="fileInput" style="display:none;" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-5">
                            <div class="product_details">
                                <div class="product_details_title">
                                    <div class="row">
                                        <div class="col-lg-8">
                                            <h2>@Model.Title</h2>
                                        </div>
                                        <div class="col-md-4 text-right">
                                            <a href="/chi-tiet-danh-muc/@Model.Alias-p@(Model.ProductCompanyId)" class="btn btn-success text-white">
                                                Xem
                                            </a>
                                        </div>
                                    </div>
                                    <hr class="col-12" />
                                </div>

                                <div class="form-group">
                                    <label>Tên hãng sản phẩm</label>
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", id = "Title" } })
                                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        <div class="form-group">
                                            <p><label>Tạo bởi :</label>@Model.CreatedBy</p>
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="form-group">
                                            <p><label>Ngày tạo :</label>@Model.CreatedDate.ToString("dd/MM/yyyy")</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        <div class="form-group">
                                            <p><label>Chỉnh sửa bởi :</label> @(Model.Modifiedby ??  "Chưa qua chỉnh sửa")</p>
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="form-group">
                                            <p><label>Ngày chỉnh sửa :</label>@(Model.ModifiedDate.HasValue ? Model.ModifiedDate.Value.ToString("dd/MM/yyyy") : "Không có ngày chỉnh sửa")</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <hr />
                            <div class="form-group text-center">
                                <div class="col-md-12">
                                    <input type="submit" value="Lưu" class="btn btn-success col-md-10" />
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-6">
                <h1 class="h3 mb-2 text-gray-800">Hệ thống quản lý</h1>
            </div>
            <div class="col-6 ">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/he-thong-quan-ly">Trang chủ</a></li>
                    <li class="breadcrumb-item"><a href="/loai-san-pham">Hãng sản phẩm</a></li>
                </ol>
            </div>
        </div>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header bg-white py-3">
                <div class="col-12">
                    <p class="text-danger text-danger">
                        Không tồn tại bảng ghi nào !!!
                    </p>
                </div>
            </div>
        </div>
    }
</div>

@section scripts{

    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
    <script>
        function BrowseServer(field) {
            var finder = new CKFinder();
            finder.selectActionFunction = function (fileUrl) {
                document.querySelector('.container-anh-moi').style.display = 'block';
                document.querySelector('.container-anh-cu').style.display = 'none';
                addImageProduct(fileUrl); 
                document.getElementById('txtImage').value = fileUrl; 
                console.log('Selected file URL:', fileUrl); 
            };
            finder.popup();
        }

        function addImageProduct(url) {
            $('#img-moi').attr('src', url);
        }
               $(document).ready(function () {
    $('#editForm').on('submit', function (e) {
        e.preventDefault();

        var formData = new FormData(this);
        var title = $('#Title').val().trim(); 

       
        if (title === '' || title === null) {
            Swal.fire({
                icon: "error",
                title: "Không thể bỏ trống...",
                text: "Vui lòng điền tên tiêu đề"
            });
            return;
        }
        // Kiểm tra nội dung FormData
        for (var pair of formData.entries()) {
            console.log(pair[0]+ ', ' + pair[1]);
        }

        $.ajax({
            url: '@Url.Action("Edit", "ProductCompany")',
            type: 'POST',
            data: formData,
            contentType: false,
            processData: false,
            success: function (response) {
                if (response.Success) {
                    if (response.Code == 1) {
                        const Toast = Swal.mixin({
                            toast: true,
                            position: "top-end",
                            showConfirmButton: false,
                            timer: 1500,
                            timerProgressBar: true,
                            didOpen: (toast) => {
                                toast.onmouseenter = Swal.stopTimer;
                                toast.onmouseleave = Swal.resumeTimer;
                            }
                        });

                        Toast.fire({
                            icon: "success",
                            title: "Sửa hãng thành công"
                        });

                        setTimeout(() => window.location.href = "/hang-san-pham", 1500);
                    }
                } else {
                    switch (response.Code) {
                        case -2:
                            Swal.fire({
                                icon: "waring",
                                title: "Thất bại ",
                                text: response.msg
                            });
                            break;

                        case -100:
                            Swal.fire({
                                icon: "error",
                                title: "Lỗi",
                                text: response.msg
                            });
                            break;
                    }
                   
                }
            },
            error: function (xhr, status, error) {
                alert('Có lỗi xảy ra: ' + error);
            }
        });
    });
});
    </script>
        
}