CuaHangBanDienThoai/CuaHangBanDienThoai/Areas/Admin/Controllers/SellerController.cs
using CuaHangBanDienThoai.Common;
using CuaHangBanDienThoai.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Drawing.Printing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using ZXing;
using ZXing.QrCode;
using A = DocumentFormat.OpenXml.Drawing;
using DW = DocumentFormat.OpenXml.Drawing.Wordprocessing;
using PIC = DocumentFormat.OpenXml.Drawing.Pictures;



using ImageProcessor.Processors;
using System.Text.RegularExpressions;
using DocumentFormat.OpenXml.Drawing.Wordprocessing;
using ZXing.QrCode.Internal;
using System.Drawing.Imaging;
using DocumentFormat.OpenXml.Drawing.Charts;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Office2010.Excel;

namespace CuaHangBanDienThoai.Areas.Admin.Controllers
{
    public class SellerController : Controller
    {
        // GET: Admin/Seller



        private CUAHANGDIENTHOAIEntities db = new CUAHANGDIENTHOAIEntities();
        [AuthorizeFunction("Nhân viên bán hàng", "Quản lý", "Quản trị viên")]
        public ActionResult Index()
        {

            var product = db.Products.ToList();
            ViewBag.Product = new SelectList(product, "ProductsId", "Title");
            ViewBag.Date=DateTime.Now.Date;
            return View();
        }
        [AuthorizeFunction("Nhân viên bán hàng", "Quản lý", "Quản trị viên")]
        public ActionResult IndexEmployye()
        {

            var product = db.Products.ToList();
            ViewBag.Product = new SelectList(product, "ProductsId", "Title");
            ViewBag.Date = DateTime.Now.Date;
            return View();
        }
        public async Task<ActionResult> Partail_ProductById(int productId)
        {
            if (productId>0&&db.ProductDetail.Any())
            {
                var pro =await db.ProductDetail.Where(x =>x.ProductsId==productId &&x.IsActive == true && x.Quantity > 0).ToListAsync();
                if (pro != null)
                {
                    ViewBag.Count = pro.Count();
                    return PartialView(pro);
                }
            }
            return PartialView();

        }
        [AuthorizeFunction( "Quản lý", "Quản trị viên")]
        public ActionResult AllBill()
        {
            DateTime selectedDate = DateTime.Now.Date;
            var bill =db.Bill.ToList();
            if (bill != null)
            {

                bool isAdmin = Session["AdminRole"] != null && Session["AdminRole"].ToString().Equals("Quản trị viên");
                bool isManage = Session["ManageRole"] != null && Session["ManageRole"].ToString().Equals("Quản lý");
                int? employeeId = ((AccountEmployee)Session["user"])?.EmployeeId;

                ViewBag.Date = DateTime.Now.Date;
                ViewBag.IsAdmin = isAdmin;

                ViewBag.CurrentEmployeeId = employeeId;
                ViewBag.Today = selectedDate.Date;
                ViewBag.IsManage = isManage;
                ViewBag.Count=bill.Count;
                return View(bill);
            }
            return View();
        }
        public ActionResult Partail_BillToday()
        {
            DateTime selectedDate = DateTime.Now.Date;



            var bill = db.Bill
                         .Where(x => DbFunctions.TruncateTime(x.CreatedDate) == selectedDate).OrderBy(x => x.BillId)
                         .ToList();
            if (bill != null &bill.Count > 0)
            {

                bool isAdmin = Session["AdminRole"] != null && Session["AdminRole"].ToString().Equals("Quản trị viên");
                bool isManage = Session["ManageRole"] != null && Session["ManageRole"].ToString().Equals("Quản lý");
                int? employeeId = ((AccountEmployee)Session["user"])?.EmployeeId;

               
                ViewBag.IsAdmin = isAdmin;

                ViewBag.CurrentEmployeeId = employeeId;

                ViewBag.IsManage = isManage;
                ViewBag.Count = bill.Count;
                ViewBag.Today = selectedDate.Date;
                return PartialView(bill);
            }
            return PartialView();
        }


        public ActionResult GetBillByDate(DateTime ngayxuat)
        {
            try
            {
                DateTime selectedDate = ngayxuat;

                DateTime startDate = selectedDate.Date;
                DateTime endDate = startDate.AddDays(1);

                var orders = db.Bill
                    .Where(o => o.CreatedDate >= startDate && o.CreatedDate < endDate)
                    .ToList();

                if (orders != null && orders.Count > 0)
                {



                    bool isAdmin = Session["AdminRole"] != null && Session["AdminRole"].ToString().Equals("Quản trị viên");
                    bool isManage = Session["ManageRole"] != null && Session["ManageRole"].ToString().Equals("Quản lý");
                    int? employeeId = ((AccountEmployee)Session["user"])?.EmployeeId;

                    // Truyền thông tin qua ViewBag
                    ViewBag.IsAdmin = isAdmin;

                    ViewBag.CurrentEmployeeId = employeeId;

                    ViewBag.IsManage = isManage;
                    ViewBag.Count = orders.Count;
                    ViewBag.Date = ngayxuat.ToString("dd/MM/yyyy");
                    ViewBag.Content = ngayxuat.ToString("dd/MM/yyyy");
                    return PartialView(orders);  
                }
                else
                {
                    ViewBag.Count = 0;
                    ViewBag.Date = ngayxuat.ToString("dd/MM/yyyy"); 
                    return PartialView(); 
                }
            }
            catch (Exception ex)
            {
                // Xử lý lỗi nếu có
                return Json(new { Success = false, Code = -99, msg = "Có lỗi xảy ra!" });
            }
        }







        [HttpGet]
        public async Task<ActionResult> SearchBill(string search)
        {

            if (Session["user"] == null)
            {
                return RedirectToAction("Account", "Login");

            }

            if (!String.IsNullOrEmpty(search))
            {

                var keyword = search.Trim().ToLower();
                var alias = CuaHangBanDienThoai.Models.Common.Filter.FilterChar(keyword);


                var querry=await (from customer in db.Customer
                                  join bill in db.Bill on customer.CustomerId equals bill.CustomerId  
                                  where customer.PhoneNumber.ToLower().Trim().Contains(keyword)||
                                       bill.Code.ToLower().Trim().Contains(keyword)  
                                       select bill  ).OrderByDescending(x=>x.CreatedDate).ToListAsync();
                bool isAdmin = Session["AdminRole"] != null && Session["AdminRole"].ToString().Equals("Quản trị viên");
                bool isManage = Session["ManageRole"] != null && Session["ManageRole"].ToString().Equals("Quản lý");
                int? employeeId = ((AccountEmployee)Session["user"])?.EmployeeId;

                // Truyền thông tin qua ViewBag
                ViewBag.IsAdmin = isAdmin;
              
                ViewBag.CurrentEmployeeId = employeeId;
               
                ViewBag.IsManage = isManage;
                if (querry.Count > 0)
                {
                    AccountEmployee nvSession = (AccountEmployee)Session["user"];


                    ViewBag.CurrentEmployeeId = employeeId;
                    var totalCount = querry.Count;
                    ViewBag.Key = search.Trim();
                    ViewBag.Count = totalCount;
                 
                    return PartialView(querry);

                }  
               
            }
            ViewBag.Key = search.Trim();
            return PartialView();
        }



        public ActionResult GetUpdatedBillRow(int billid)
        {

            var bill = db.Bill.FirstOrDefault(b => b.BillId == billid);
            if (bill != null)
            {
                return PartialView(bill);
            }
            return HttpNotFound();
        }




        public ActionResult Partial_BillByEmployee(int? employeeid)
        {

            if (Session["user"] != null&& employeeid ==null)
            {
                AccountEmployee nvSession = (AccountEmployee)Session["user"];
                employeeid=(int)nvSession.EmployeeId;   

            }
            if(employeeid>0)
            {
                var bill=db.Bill.Where(x=>x.EmployeeId==employeeid).OrderByDescending(x=>x.CreatedDate).ToList();   
                if(bill != null)
                {
                    ViewBag.EmployeeId = employeeid;    
                    ViewBag.Count=bill.Count(); 
                    return PartialView(bill);   
                }   
            }
            return PartialView();
        }
        public ActionResult Partail_BillDetail(int billid)
        {
            if (billid > 0)
            {
                var billdetail=db.BillDetail.Where(x=>x.BillId==billid).ToList();
                if (billdetail != null)
                {
                    return  PartialView(billdetail);        
                }
            }
            return PartialView();
        }


        public ActionResult Partail_Product()
        {
            if (db.ProductDetail.Any())
            {
                var pro =db.ProductDetail.Where(x=>x.IsActive==true&& x.Quantity>0).ToList();
                if (pro != null)
                {
                    ViewBag.Count=pro.Count();    
                    return PartialView(pro);    
                }
            }
            return PartialView();   

        }
        public ActionResult Partial_ListProductBill()
        {
            SellerCart cart = (SellerCart)Session["SellerCart"];

CuaHangBanDienThoai/CuaHangBanDienThoai/Areas/Admin/Views/Seller/AllBill.cshtml
@model IEnumerable<CuaHangBanDienThoai.Models.Bill>
    @using CuaHangBanDienThoai.Common;
@{
    ViewBag.Title = "Tất cả hoá đơn";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<style>
    .table-scroll {
        max-height: 680px;
        overflow-y: auto;
    }

    thead th,
    tbody td {
        text-align: center;
    }

    table {
        table-layout: fixed;
        width: 100%;
    }

    thead th {
        position: sticky;
        top: 0;
        background-color: #f8f9fa;
        z-index: 2;
    }

    .table-scroll::-webkit-scrollbar {
        width: 0px;
    }

    .table-scroll {
        scrollbar-width: none;
    }
</style>


<link href="~/Content/css/admin/SellerIndex.css" rel="stylesheet" />
<div class="bg-sg" style="display: none ">

</div>


<div id="popupBill" style="display: none ">
    @*@Html.Action("Partail_AddCustomer","Seller")*@

</div>

<div class="container-fluid p-0 m-0">
    <!-- Page Heading -->
    <div class="row">
        <div class="col-6">
            <h1 class="h3 mb-2 text-gray-800">Hệ thống quản lý hoá đơn </h1>


        </div>
        <div class="col-6 ">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/hethongquanly">Trang chủ </a></li>

                <li class="breadcrumb-item active">Quản lý hoá đơn </li>

            </ol>

        </div>
    </div>

    <!-- DataTales Example -->
    <div class="card border-top-0  mb-4 " style="height:auto;background-color:transparent">
        <div class="card-header p-0 m-0  border-top-0 " style="height:auto;background-color:transparent">
            <nav class="mb-0">
                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Tất cả hoá đơn</button>
                    <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Hoá đơn hôm nay @String.Format("{0:dd/MM/yyyy}", ViewBag.Date??"")</button>
                </div>
            </nav>
        </div>

        <div class="card-body  p-0 " id="loaddata">
            <div class="row bg-white pb-4">
                <div class="col-12 col-sm-12 col-md-12 col-lg-12 p-0 ">

                    <div class="tab-content bg-white  m-0 p-0 pr-2 pl-2 w-100" id="nav-tabContent">
                        <div class="tab-pane m-2 mt-3 fade active show" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                            <div class="row p-0 ml-1 mr-1 pb-4 mt-3 w-100">
                                <div class="card w-100">
                                    <div class="card-header bg-white py-3">
                                        <div class="row">
                                            <div class="col-2 " id="loadTitle">
                                                <h6 class="m-0 font-weight-bold text-primary">
                                                  Tất cả hoá đơn
                                                </h6>
                                            </div>

                                            <div class="col-10 text-right">


                                                <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                                                    <div class="input-group">
                                                        <input type="datetime-local" class="form-control bg-light border-0 small" placeholder="Tìm đơn hàng..."
                                                               aria-label="Search" aria-describedby="basic-addon2" id="DateBill">
                                                        <div class="input-group-append">
                                                            <button class="btn bg-light btnclearSBill" data-employeeid="@(ViewBag.EmployeeId??"")" type="button" id="clearInputBill">
                                                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-x" viewBox="0 0 16 16">
                                                                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708" />
                                                                </svg>
                                                            </button>
                                                        </div>

                                                    </div>
                                                </form>

                                                <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                                                    <div class="input-group">
                                                        <input type="text" class="form-control bg-light border-0 small" id="searchBill" placeholder="Tìm đơn hàng..."
                                                               aria-label="Search" aria-describedby="basic-addon2">
                                                        <div class="input-group-append">
                                                            <button class="btn bg-light btnclearSBill" data-employeeid="@(ViewBag.EmployeeId??"")" type="button" id="clearInputBill">
                                                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-x" viewBox="0 0 16 16">
                                                                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708" />
                                                                </svg>
                                                            </button>
                                                        </div>
                                                        <div class="input-group-append">
                                                            <button class="btn btn-primary" type="button">
                                                                <i class="fas fa-search fa-sm"></i>
                                                            </button>
                                                        </div>
                                                    </div>
                                                </form>

                                            </div>
                                        </div>

                                    </div>
                                    <div class="card-body p-0 m-0 w-100" style="">
                                        <table class="table table-bordered mb-0" id="dataTable" style="table-layout: fixed; width: 100%;">
                                            <thead>
                                                <tr class="text-center">
                                                    <th style="width: 10%;">Mã đơn</th>
                                                    <th style="width: 30%;">Khách hàng</th>
                                                    <th style="width: 30%;">Sản phẩm</th>
                                                    <th style="width: 20%;">Tổng tiền</th>
                                                    <th style="width: 10%;"></th>
                                                </tr>
                                            </thead>
                                        </table>
                                        <div class="table-scroll" id="loadbill">

                                            <div class="text-center loadding"> <img src="/images/gif/loading.gif" style="display:none" /></div>
                                            <table class="table table-bordered" id="dataTableBody" style="table-layout: fixed; width: 100%;">
                                                <tbody>
                                                    @if (Model != null)
                                                    {
                                                        foreach (var item in Model)
                                                        {


                                                            <tr class="row_content tr_IndexBill_@item.BillId" id="tr_IndexBill_@item.BillId">
                                                                <td class="code-container" style="width: 10%;">
                                                                    <span class="code-text">@item.Code.Trim()</span>
                                                                </td>
                                                                <td style="width: 30%;">
                                                                    <div class="row">
                                                                        <b>
                                                                            <i class="fa fa-user" aria-hidden="true"></i>
                                                                            :
                                                                        </b> @item.Customer.CustomerName.Trim()
                                                                    </div>
                                                                    <div class="row">
                                                                        <b><i class="fa fa-phone-square" aria-hidden="true"></i> :</b> @item.Customer.PhoneNumber.Trim()
                                                                    </div>

                                                                    <div class="row">
                                                                        <b><i class="fa fa-calendar" aria-hidden="true"></i>:</b> @String.Format("{0:dd/MM/yyyy HH:mm:ss}", item.CreatedDate)

                                                                    </div>
                                                                    <div class="row">
                                                                        <b>
                                                                            Nhân viên bán hàng :
                                                                        </b> @item.Employee.NameEmployee.Trim()
                                                                    </div>
                                                                </td>
                                                                <td style="width: 30%;">@Html.Action("Partail_BillDetail", "Seller", new { billid = item.BillId })</td>
                                                                <td style="width: 20%;">@($"{Common.FormatNumber(item.TotalAmount)}đ")</td>
                                                                <td class=" align-items-center" style="width: 10%;">
                                                                    <button type="button" class="btn btn-warning d-flex align-items-center justify-content-center w-100 btnupdatebill"
                                                                            data-billid="@item.BillId" style="height: 40px;">
                                                                        <img src="~/images/gif/Spinnerloading.gif" class="loading-image" style="width: 45px; height: 45px; display: none;" />
                                                                        <span class="button-text">Cập nhật</span>
                                                                    </button>
                                                                </td>

                                                            </tr>
                                                        }
                                                    }
                                                </tbody>
                                            </table>
                                        </div>



                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade    bg-white  m-0 p-0 pr-2 pl-2 w-100 pb-4 loadAllBill" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab" style="height: 800px ">
                          @Html.Action("Partail_BillToday","Seller")


                        </div>
                    </div>
                </div>


            </div>



        </div>
    </div>
</div>
@section scripts{
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
    <script src="~/Scripts/admin/Seller_Index.js"></script>

}

CuaHangBanDienThoai/CuaHangBanDienThoai/Areas/Admin/Views/Seller/GetUpdatedBillRow.cshtml
@model CuaHangBanDienThoai.Models.Bill
@using CuaHangBanDienThoai.Common;
@if (Model != null)
{
    <tr class="row_content tr_IndexBill_@Model.BillId" id="tr_IndexBill_@Model.BillId">
        <td class="code-container" style="width: 10%;">
            <span class="code-text">@Model.Code.Trim()</span>
        </td>
        <td style="width: 30%;">
            <div class="row">
                <b>
                    <i class="fa fa-user" aria-hidden="true"></i>
                    :
                </b> @Model.Customer.CustomerName.Trim()
            </div>
            <div class="row">
                <b><i class="fa fa-phone-square" aria-hidden="true"></i> :</b> @Model.Customer.PhoneNumber.Trim()
            </div>
            <div class="row">
                <b><i class="fa fa-calendar" aria-hidden="true"></i>:</b> @String.Format("{0:dd/MM/yyyy HH:mm:ss}", Model.CreatedDate)
            </div>
        </td>
        <td style="width: 30%;">@Html.Action("Partail_BillDetail", "Seller", new { billid = Model.BillId })</td>
        <td style="width: 20%;">@($"{Common.FormatNumber(Model.TotalAmount)}đ")</td>
        <td class=" align-Models-center" style="width: 10%;">
            <button type="button" class="btn btn-warning d-flex align-Models-center justify-content-center w-100 btnupdatebill"
                    data-billid="@Model.BillId" style="height: 40px;">
                <img src="~/images/gif/Spinnerloading.gif" class="loading-image" style="width: 45px; height: 45px; display: none;" />
                <span class="button-text">Cập nhật</span>
            </button>
        </td>

    </tr>
}

CuaHangBanDienThoai/CuaHangBanDienThoai/Areas/Admin/Views/Seller/Partail_BillDetail.cshtml
@model IEnumerable<CuaHangBanDienThoai.Models.BillDetail>

@if (Model != null)
{
    foreach (var item in Model)
    {
        var Name = item.ProductDetail.Products.Title.Trim() + " " + item.ProductDetail.Ram.Trim() + "/" + item.ProductDetail.Capacity.Trim();
        <div class="d-flex p-0">
            <span class="text-dark">@Name.Trim()</span>

            <span class="pl-1 text-danger">x @item.Quantity</span>
        </div>


    }
}
else
{
    <p class="text-danger text-center">Lỗi dữ liệu </p>
}

CuaHangBanDienThoai/CuaHangBanDienThoai/Areas/Admin/Views/Seller/Partail_BillToday.cshtml
@model IEnumerable<CuaHangBanDienThoai.Models.Bill>
@using CuaHangBanDienThoai.Common;

<div class="row p-0 ml-1 mr-1 pb-4 mt-3 w-100">
    <div class="card w-100">
        <div class="card-header bg-white py-3">
            <div class="row">
                <div class="col-4 " id="loadTitle">
                    <h6 class="m-0 font-weight-bold text-primary "> Hoá đơn bán ngày : <span class="ml-2 text-danger" style="font-size:16px;"> @(String.Format("{0:dd/MM/yyyy}", ViewBag.Today??""))</span>
                        <br />
                        <span class="text-danger "> <label class="text-dark">Tổng số hoá đơn:</label>     <span id="totalCount">@ViewBag.Count</span></span>
                    </h6>
           
                </div>

                <div class="col-8 text-right">

                </div>
            </div>

        </div>
        <div class="card-body p-0 m-0 w-100" style="">
            <table class="table table-bordered mb-0" id="dataTable" style="table-layout: fixed; width: 100%;">
                <thead>
                    <tr class="text-center">
                        <th style="width: 10%;">Mã đơn</th>
                        <th style="width: 30%;">Khách hàng</th>
                        <th style="width: 30%;">Sản phẩm</th>
                        <th style="width: 20%;">Tổng tiền</th>
                        <th style="width: 10%;"></th>
                    </tr>
                </thead>
            </table>
            <div class="table-scroll" id="loadbill">

                <div class="text-center loadding"> <img src="/images/gif/loading.gif" style="display:none" /></div>
                <table class="table table-bordered" id="dataTableBody" style="table-layout: fixed; width: 100%;">
                    <tbody>

                        @if (Model != null&&Model.Any())
                        {
                            foreach (var item in Model)
                            {


                                <tr class="row_content tr_IndexBill_@item.BillId" id="tr_IndexBill_@item.BillId">
                                    <td class="code-container" style="width: 10%;">
                                        <span class="code-text">@item.Code.Trim()</span>
                                    </td>
                                    <td style="width: 30%;">
                                        <div class="row">
                                            <b>
                                                <i class="fa fa-user" aria-hidden="true"></i>
                                                :
                                            </b> @item.Customer.CustomerName.Trim()
                                        </div>
                                        <div class="row">
                                            <b><i class="fa fa-phone-square" aria-hidden="true"></i> :</b> @item.Customer.PhoneNumber.Trim()
                                        </div>

                                        <div class="row">
                                            <b><i class="fa fa-calendar" aria-hidden="true"></i>:</b> @String.Format("{0:dd/MM/yyyy HH:mm:ss}", item.CreatedDate)

                                        </div>
                                        <div class="row">
                                            <b>
                                                Nhân viên bán hàng :
                                            </b> @item.Employee.NameEmployee.Trim()
                                        </div>
                                    </td>
                                    <td style="width: 30%;">@Html.Action("Partail_BillDetail", "Seller", new { billid = item.BillId })</td>
                                    <td style="width: 20%;">@($"{Common.FormatNumber(item.TotalAmount)}đ")</td>
                                    <td class=" align-items-center" style="width: 10%;">
                                        <button type="button" class="btn btn-warning d-flex align-items-center justify-content-center w-100 btnupdatebill"
                                                data-billid="@item.BillId" style="height: 40px;">
                                            <img src="~/images/gif/Spinnerloading.gif" class="loading-image" style="width: 45px; height: 45px; display: none;" />
                                            <span class="button-text">Cập nhật</span>
                                        </button>
                                    </td>

                                </tr>
                            }
                        }
else
            {
                <tr>
                    <td colspan="5">
                        <p class="text-danger">Không tồn tại hoá đơn ngày @ViewBag.Today </p>
                    </td>
                </tr>
            }
                    </tbody>
                </table>
            </div>



        </div>
    </div>
</div>